### ISSUE TITLE
How add extra parameters to googleOAuth2Details?

### ISSUE THREAD

**Issue by kdekooter** [fromi/spring-google-openidconnect#2]
I am migrating from OpenID to OpenID Connect. Now Google advises to add the `openid.realm` parameter and an `id_token` to the authentication request URI (see https://developers.google.com/accounts/docs/OpenID for details) so the old identifier can be mapped to the new one.
How can this be done? Should I subclass `BaseOAuth2ProtectedResourceDetails`?

**Comment by fromi** [comment]
Don't know that, but you can have a look at Spring OAuth2ClientContextFilter, it is the class that redirects to Google, and based on that look at the best way to inject your custom parameters.
Good luck

**Comment by kdekooter** [comment]
I'll start digging. Thanks!
